# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 土木工学科ポータルサイト
email: nakamura.hideo74@nihon-u.ac.jp
baseurl: ""
url: "https://cve-cst.github.io"
plugins:
  - jekyll-sitemap

# Build settings
sass:
  sass_dir: _sass
include: ['_pages','.htaccess']
markdown: kramdown
kramdown:
  input: GFM
